### ISSUE TITLE
Proxy is being added whether it need it or not

### ISSUE THREAD

**Issue by joelfriesen** [cioos-siooc/cioos-siooc-assetmap#43]
in asset_ckan.js there is a line near 267 that asks to find a proxy, but if it doesn't have one it tries to insert an undefined one

       else if (this.ckan_proxy_name !== undefined)
        {
            // since no jsonp and name of proxy define then add proxy info to url
            ret_url += this.ckan_proxy_name + '/';
        }

Should be 

 
        else if (this.ckan_proxy_name !== undefined)
        {
            // since no jsonp and name of proxy define then add proxy info to url
            ret_url += '/';
        }

I think???

**Comment by sauve** [comment]
Since the proxy can support multiple ckan instance with multiple client concurrently, it is stateless and requires that the client specify the ckan instance it wants to communicate with. Normally, once the ckan is in the website and using a cioos ckan config, it should be able to talk to it directly using jsonp and bypass the proxy entirely. This is there mostly for debugging.
