### ISSUE TITLE
Extra request to API

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/cioos-siooc-assetmap#58]
Even if `page_size` is set very high, it seems there is still an extra request for the first 5 records and then a request for the next `page_size` records (defaults to 40). I'm not sure that this is a bug but it seems like one.

Tested with CKAN national, setting page_size=4000, when a filter is selected there are 2 API calls instead of one -

```
https://cnckan.cioos.ca/api/3/action/package_search?fl=id,title_translated,notes_translated,eov,keywords,spatial&fq=eov:(seaSurfaceTemperature OR potentialTemperature OR subSurfaceTemperature)&rows=5&start=0&callback=jsonpcallback

and

https://cnckan.cioos.ca/api/3/action/package_search?fl=id,title_translated,notes_translated,eov,keywords,spatial&fq=eov:(seaSurfaceTemperature OR potentialTemperature OR subSurfaceTemperature)&rows=4000&start=5&callback=jsonpcallback

```

**Comment by sauve** [comment]
This isn't a bug, it's a feature ;-)

Seriously, there should have been another option to customize the original request size, since some CKAN instance were pretty slow to respond. This was to give a bettre interactivity. I will add the initial page request size as an option. This could be set to a very large number a the pagination will only kick in once we have much more data.

**Comment by n-a-t-e** [comment]
I see! Thanks, will be handy to have initial page request size as a configurable option

**Comment by sauve** [comment]
Added the "initial_page_size" in the json ckan config.
